// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityContext))]
    [Migration("20220707085425_CityInfoDBDummyData")]
    partial class CityInfoDBDummyData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wo ich meine Ehre verloren hab",
                            Name = "Basel"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ultra hübsch",
                            Name = "Bern"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hat Oerlikon LMAO",
                            Name = "Zürich"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Wo ich meine Ehre verloren hab",
                            Name = "Zoo Basel"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Wait, ist das dort meine Ehre??",
                            Name = "Meine Ehre"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Tun so als wären sie ultra homies mit Einstein",
                            Name = "Uni Bern"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Loser muss immer lernen",
                            Name = "Rinesas Ehre"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Description = "LMAO",
                            Name = "Oerlikon"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Description = "Zürich ist verbrannt, whoops",
                            Name = "Töbes Ehre"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
